resources:
  repositories:
    - repository: templates
      type: github
      endpoint: piomin
      name: piomin/azure-pipelines-templates
      ref: refs/heads/master

trigger:
- master

pool:
  name: Azure Pipelines

stages:
  - template: dotnet-library-stage.yml@templates
    parameters:
      projectPath: 'src/WebApi.Library/WebApi.Library.csproj'
      testProjectPath: 'tests/WebApi.Library.Tests/WebApi.Library.Tests.csproj'
      feedName: 'pminkows'