trigger:
- master
- test

pool:
  name: Azure Pipelines

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  projectPath: 'src/WebApi.Library/WebApi.Library.csproj'
  testProjectPath: 'tests/WebApi.Library.Tests/WebApi.Library.Tests.csproj'
  buildArtifactName: 'drop'


stages:
- stage: Build
  displayName: 'Build and Test'
  jobs:
  - job: Build_And_Test
    steps:
    - task: UseDotNet@2
      displayName: 'Use .NET 9.x'
      inputs:
        version: '9.x'

    - task: DotNetCoreCLI@2
      displayName: 'Restore NuGet packages'
      inputs:
        command: 'restore'
        projects: '$(projectPath)'

    - task: DotNetCoreCLI@2
      displayName: 'Build solution'
      inputs:
        command: 'build'
        projects: '$(projectPath)'
        arguments: '-c $(buildConfiguration) --no-restore'

    - task: DotNetCoreCLI@2
      displayName: 'Run tests'
      inputs:
        command: 'test'
        projects: '$(testProjectPath)'
        arguments: '-c $(buildConfiguration)'
        publishTestResults: true
        testRunTitle: 'Unit Tests'

    - task: DotNetCoreCLI@2
      displayName: 'Pack NuGet package'
      inputs:
        command: 'pack'
        packagesToPack: '$(projectPath)'
        arguments: '-c $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/packages'

- stage: Pack
  displayName: 'Create NuGet package'
  dependsOn: Build
  condition: succeeded()
  jobs:
  - job: Pack
    steps:
    - task: DotNetCoreCLI@2
      displayName: 'Pack NuGet package'
      inputs:
        command: 'pack'
        packagesToPack: '$(projectPath)'
        arguments: '-c $(buildConfiguration) --no-build --output $(Build.ArtifactStagingDirectory)/packages'

    - publish: '$(Build.ArtifactStagingDirectory)/packages'
      artifact: '$(buildArtifactName)'
      displayName: 'Publish Artifact'

- stage: Publish
  displayName: 'Publish to Azure Artifacts'
  dependsOn: Pack
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  jobs:
  - job: Publish
    steps:
    - task: NuGetAuthenticate@1
      displayName: 'Authenticate with Azure Artifacts'

    - task: NuGetCommand@2
      displayName: 'Push to Azure Artifacts'
      inputs:
        command: 'push'
        packagesToPush: '$(Build.ArtifactStagingDirectory)/packages/*.nupkg'
        nuGetFeedType: 'internal'
        publishVstsFeed: 'pminkows'  # This should be your Azure DevOps feed name
        allowPackageConflicts: false
