version: 2.1

orbs:
  docker: circleci/docker@2.8.2

executors:
  dotnet:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:9.0

jobs:
  build-and-test:
    executor:
      name: dotnet
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: dotnet restore
      - run:
          name: Build
          command: dotnet build
      - run:
          name: Tests
          command: dotnet test
workflows:
  build-and-test:
    jobs:
      - build-and-test